name: dbt CI

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  dbt-run:
    name: Prod deps and runn
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT:  "${{ secrets.SNOWFLAKE_ACCOUNT }}"
      SNOWFLAKE_USER:     "${{ secrets.SNOWFLAKE_USER }}"
      SNOWFLAKE_PASSWORD: "${{ secrets.SNOWFLAKE_PASSWORD }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
    
      - run: uv python install 3.12
      - run: uv sync
      - run: cd btc && uv run dbt deps --target prod
      - run: cd btc && uv run dbt build --target prod
